# Generated by Django 2.1.8 on 2019-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='three_four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido_nm', models.CharField(blank=True, max_length=15)),
                ('sigun_nm', models.CharField(blank=True, max_length=10)),
                ('gagu_count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIDO_NM', models.CharField(blank=True, max_length=15)),
                ('SIGUN_NM', models.CharField(blank=True, max_length=10)),
                ('ADDR', models.CharField(blank=True, max_length=100)),
                ('LOT_AREA', models.IntegerField(blank=True)),
                ('BUILDING_AREA', models.IntegerField(blank=True)),
                ('OWNER_NM', models.CharField(blank=True, max_length=10)),
                ('OWNER_CONTACT', models.IntegerField(blank=True)),
                ('BIGO', models.CharField(blank=True, max_length=100)),
                ('FILE_PATH1', models.CharField(blank=True, max_length=100)),
                ('FILE_PATH2', models.CharField(blank=True, max_length=100)),
                ('FILE_PATH3', models.CharField(blank=True, max_length=100)),
                ('REG_DT', models.CharField(blank=True, max_length=20)),
                ('DEAL_TYPE', models.CharField(blank=True, max_length=50)),
                ('RETURN_PEOPLE', models.IntegerField(default='0')),
            ],
        ),
    ]
