# Generated by Django 2.1.8 on 2019-06-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='BUILDING_AREA',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='LOT_AREA',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='OWNER_CONTACT',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
